sudo: required

language: node_js

node_js:
  - "node"
  - "8"

services:
  - docker

before_install:
  - docker build -t kostola/telegram-bot .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push kostola/telegram-bot;
    fi

script:
  - npm test
